`default_nettype none

module ace2_shell_runtime_harness (
    input  wire          clk_i,
    input  wire          rst_ni,

    input  wire          csr_valid_i,
    output wire          csr_ready_o,
    input  wire          csr_write_i,
    input  wire [31:0]   csr_addr_i,
    input  wire [63:0]   csr_wdata_i,
    input  wire [7:0]    csr_wstrb_i,
    output wire          csr_rvalid_o,
    input  wire          csr_rready_i,
    output wire [63:0]   csr_rdata_o,
    output wire          csr_error_o,
    output wire          irq_o,

    input  wire          cmd_valid_i,
    output wire          cmd_ready_o,
    input  wire [7:0]    cmd_opcode_i,
    input  wire [7:0]    cmd_flags_i,
    input  wire [7:0]    cmd_layer_id_i,
    input  wire [15:0]   cmd_m_i,
    input  wire [15:0]   cmd_n_i,
    input  wire [15:0]   cmd_k_i,
    input  wire [15:0]   cmd_sequence_position_i,
    input  wire [15:0]   cmd_completion_tag_i,
    input  wire [63:0]   cmd_src0_addr_i,
    input  wire [63:0]   cmd_src1_addr_i,
    input  wire [63:0]   cmd_dst_addr_i,
    input  wire [63:0]   cmd_scale_addr_i,
    input  wire [63:0]   cmd_scratch_addr_i,

    output wire          mem_req_valid_o,
    input  wire          mem_req_ready_i,
    output wire          mem_req_write_o,
    output wire [63:0]   mem_req_addr_o,
    output wire [15:0]   mem_req_len_o,
    output wire [7:0]    mem_req_tag_o,
    output wire          mem_wvalid_o,
    input  wire          mem_wready_i,
    output wire [127:0]  mem_wdata_o,
    output wire [15:0]   mem_wstrb_o,
    output wire [7:0]    mem_wtag_o,
    input  wire          mem_rvalid_i,
    output wire          mem_rready_o,
    input  wire [127:0]  mem_rdata_i,
    input  wire [7:0]    mem_rtag_i,
    input  wire          mem_rerror_i,
    input  wire          mem_bvalid_i,
    output wire          mem_bready_o,
    input  wire [7:0]    mem_btag_i,
    input  wire          mem_berror_i,

    output wire          busy_o,
    output wire          cmd_done_valid_o,
    input  wire          cmd_done_ready_i,
    output wire [15:0]   cmd_done_tag_o,
    output wire          cmd_done_error_o,
    output wire [47:0]   cmd_done_sumsq_o,
    output wire [31:0]   cmd_done_inv_rms_q30_o,
    output wire          cmd_done_saturation_seen_o
);
    wire [7:0] sram_req_valid_unused;
    wire [7:0] sram_write_unused;
    wire [8*12-1:0] sram_addr_unused;
    wire [8*128-1:0] sram_wdata_unused;
    wire [8*16-1:0] sram_wstrb_unused;

    ace2_shell dut (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .csr_valid_i(csr_valid_i),
        .csr_ready_o(csr_ready_o),
        .csr_write_i(csr_write_i),
        .csr_addr_i(csr_addr_i),
        .csr_wdata_i(csr_wdata_i),
        .csr_wstrb_i(csr_wstrb_i),
        .csr_rvalid_o(csr_rvalid_o),
        .csr_rready_i(csr_rready_i),
        .csr_rdata_o(csr_rdata_o),
        .csr_error_o(csr_error_o),
        .irq_o(irq_o),
        .cmd_valid_i(cmd_valid_i),
        .cmd_ready_o(cmd_ready_o),
        .cmd_opcode_i(cmd_opcode_i),
        .cmd_flags_i(cmd_flags_i),
        .cmd_layer_id_i(cmd_layer_id_i),
        .cmd_m_i(cmd_m_i),
        .cmd_n_i(cmd_n_i),
        .cmd_k_i(cmd_k_i),
        .cmd_sequence_position_i(cmd_sequence_position_i),
        .cmd_completion_tag_i(cmd_completion_tag_i),
        .cmd_src0_addr_i(cmd_src0_addr_i),
        .cmd_src1_addr_i(cmd_src1_addr_i),
        .cmd_dst_addr_i(cmd_dst_addr_i),
        .cmd_scale_addr_i(cmd_scale_addr_i),
        .cmd_scratch_addr_i(cmd_scratch_addr_i),
        .mem_req_valid_o(mem_req_valid_o),
        .mem_req_ready_i(mem_req_ready_i),
        .mem_req_write_o(mem_req_write_o),
        .mem_req_addr_o(mem_req_addr_o),
        .mem_req_len_o(mem_req_len_o),
        .mem_req_tag_o(mem_req_tag_o),
        .mem_wvalid_o(mem_wvalid_o),
        .mem_wready_i(mem_wready_i),
        .mem_wdata_o(mem_wdata_o),
        .mem_wstrb_o(mem_wstrb_o),
        .mem_wtag_o(mem_wtag_o),
        .mem_rvalid_i(mem_rvalid_i),
        .mem_rready_o(mem_rready_o),
        .mem_rdata_i(mem_rdata_i),
        .mem_rtag_i(mem_rtag_i),
        .mem_rerror_i(mem_rerror_i),
        .mem_bvalid_i(mem_bvalid_i),
        .mem_bready_o(mem_bready_o),
        .mem_btag_i(mem_btag_i),
        .mem_berror_i(mem_berror_i),
        .sram_req_valid_o(sram_req_valid_unused),
        .sram_req_ready_i(8'hff),
        .sram_write_o(sram_write_unused),
        .sram_addr_o(sram_addr_unused),
        .sram_wdata_o(sram_wdata_unused),
        .sram_wstrb_o(sram_wstrb_unused),
        .sram_rdata_i({8*128{1'b0}}),
        .sram_rvalid_i(8'h00),
        .busy_o(busy_o),
        .cmd_done_valid_o(cmd_done_valid_o),
        .cmd_done_ready_i(cmd_done_ready_i),
        .cmd_done_tag_o(cmd_done_tag_o),
        .cmd_done_error_o(cmd_done_error_o),
        .cmd_done_sumsq_o(cmd_done_sumsq_o),
        .cmd_done_inv_rms_q30_o(cmd_done_inv_rms_q30_o),
        .cmd_done_saturation_seen_o(cmd_done_saturation_seen_o)
    );
endmodule

`default_nettype wire
