#!/usr/bin/env python3
"""Generate cross-tile long-context attention vectors."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from ace2_attention_compose_reference import (
    HEAD_DIM,
    AttentionComposeCase,
    reference_attention_compose,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "attention_compose_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "attention_compose_vectors.json"
TILE = 8
MAX_CONTEXT = 17
MAX_TILES = (MAX_CONTEXT + TILE - 1) // TILE
BEATS = HEAD_DIM // 16


def _values(context: int, salt: int) -> list[list[int]]:
    return [
        [
            ((token * (11 + salt) + lane * (3 + token % 5) + 37) % 256) - 128
            for lane in range(HEAD_DIM)
        ]
        for token in range(context)
    ]


def _cases() -> list[AttentionComposeCase]:
    return [
        AttentionComposeCase(
            "first_cross_tile_9",
            [256, -64, 448, 0, -512, 192, 64, -1024, 512],
            _values(9, 1),
        ),
        AttentionComposeCase(
            "exact_two_tiles_16",
            [((index * 173 + 91) % 2048) - 1024 for index in range(16)],
            _values(16, 2),
        ),
        AttentionComposeCase(
            "partial_third_tile_17",
            [((index * 251 + 777) % 4096) - 2048 for index in range(17)],
            _values(17, 3),
        ),
    ]


def _pack(values: list[int], width: int) -> int:
    packed = 0
    mask = (1 << width) - 1
    for lane, value in enumerate(values):
        packed |= (value & mask) << (lane * width)
    return packed


def _hex(value: int, bits: int) -> str:
    return f"{bits}'h{value & ((1 << bits) - 1):0{bits // 4}x}"


def _digest(values: list[int], width: int) -> str:
    byte_width = width // 8
    mask = (1 << width) - 1
    return hashlib.sha256(
        b"".join((value & mask).to_bytes(byte_width, "little") for value in values)
    ).hexdigest()


def main() -> None:
    cases = _cases()
    lines = [
        "// Generated by tools/gen_attention_compose_vectors.py; do not edit.",
        f"localparam integer ATTN_COMPOSE_CASE_COUNT = {len(cases)};",
        f"localparam integer ATTN_COMPOSE_TILE = {TILE};",
        f"localparam integer ATTN_COMPOSE_MAX_CONTEXT = {MAX_CONTEXT};",
        f"localparam integer ATTN_COMPOSE_MAX_TILES = {MAX_TILES};",
        f"localparam integer ATTN_COMPOSE_BEATS = {BEATS};",
        "reg [15:0] attn_compose_context_count [0:ATTN_COMPOSE_CASE_COUNT-1];",
        "reg [127:0] attn_compose_score_tiles [0:ATTN_COMPOSE_CASE_COUNT*ATTN_COMPOSE_MAX_TILES-1];",
        "reg [127:0] attn_compose_value_beats [0:ATTN_COMPOSE_CASE_COUNT*ATTN_COMPOSE_MAX_CONTEXT*ATTN_COMPOSE_BEATS-1];",
        "reg [127:0] attn_compose_expected_beats [0:ATTN_COMPOSE_CASE_COUNT*ATTN_COMPOSE_BEATS-1];",
        "reg attn_compose_expected_saturation [0:ATTN_COMPOSE_CASE_COUNT-1];",
        "initial begin",
    ]
    records = []
    for case_index, case in enumerate(cases):
        result = reference_attention_compose(case)
        context = len(case.scores_q6_9)
        lines.append(
            f"  attn_compose_context_count[{case_index}] = 16'd{context};"
        )
        for tile in range(MAX_TILES):
            scores = case.scores_q6_9[tile * TILE : (tile + 1) * TILE]
            scores += [0] * (TILE - len(scores))
            lines.append(
                f"  attn_compose_score_tiles[{case_index * MAX_TILES + tile}] = "
                f"{_hex(_pack(scores, 16), 128)};"
            )
        padded_values = case.values + [
            [0] * HEAD_DIM for _ in range(MAX_CONTEXT - context)
        ]
        for token, row in enumerate(padded_values):
            for beat in range(BEATS):
                flat = (
                    case_index * MAX_CONTEXT * BEATS + token * BEATS + beat
                )
                word = _pack(row[beat * 16 : (beat + 1) * 16], 8)
                lines.append(
                    f"  attn_compose_value_beats[{flat}] = {_hex(word, 128)};"
                )
        for beat in range(BEATS):
            flat = case_index * BEATS + beat
            word = _pack(result.outputs[beat * 16 : (beat + 1) * 16], 8)
            lines.append(
                f"  attn_compose_expected_beats[{flat}] = {_hex(word, 128)};"
            )
        lines.append(
            f"  attn_compose_expected_saturation[{case_index}] = "
            f"1'b{int(result.saturation_seen)};"
        )
        records.append(
            {
                "name": case.name,
                "context_count": context,
                "tile_count": (context + TILE - 1) // TILE,
                "score_sha256": _digest(case.scores_q6_9, 16),
                "value_sha256": _digest(
                    [value for row in case.values for value in row], 8
                ),
                "probability_sha256": _digest(result.probabilities_q15, 16),
                "output_sha256": _digest(result.outputs, 8),
                "max_score_q6_9": result.max_score_q6_9,
                "exp_sum_q15": result.exp_sum_q15,
                "saturation_seen": result.saturation_seen,
            }
        )
    lines.append("end")
    OUT_SVH.parent.mkdir(parents=True, exist_ok=True)
    OUT_SVH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "generator": "tools/gen_attention_compose_vectors.py",
                "reference": "tools/ace2_attention_compose_reference.py",
                "context_max": 32768,
                "tile_size": TILE,
                "score_format": "signed_int16 Q6.9",
                "probability_format": "unsigned_int16 Q0.15",
                "value_format": "signed_int8",
                "rounding": "ties_to_even",
                "cases": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
