#!/usr/bin/env python3
"""Generate ACE-2 attention-score RTL vectors from the Python reference."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from ace2_attention_score_reference import (
    BEATS_PER_VECTOR,
    CONTEXT_MAX,
    HEAD_DIM,
    MAC_LANES,
    AttentionScoreCase,
    pack_int16,
    pack_int8,
    pack_score_metadata,
    reference_attention_score,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "attention_score_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "attention_score_vectors.json"


def _identity_like_case() -> AttentionScoreCase:
    q_values = [((index * 5 + 3) % 17) - 8 for index in range(HEAD_DIM)]
    k_values = [
        [((index * 7 + token * 11 + 1) % 19) - 9 for index in range(HEAD_DIM)]
        for token in range(1)
    ]
    return AttentionScoreCase("single_token_mixed_sign", q_values, k_values)


def _rounding_tie_case() -> AttentionScoreCase:
    q_values = [0 for _ in range(HEAD_DIM)]
    q_values[0:4] = [1, 1, 1, 1]
    k_values = [
        [0 for _ in range(HEAD_DIM)],
        [0 for _ in range(HEAD_DIM)],
        [0 for _ in range(HEAD_DIM)],
    ]
    k_values[0][0:4] = [1, 1, 1, 1]
    k_values[1][0:4] = [1, 1, 1, 3]
    k_values[2][0:4] = [-1, -1, -1, -1]
    return AttentionScoreCase("round_to_even_edges", q_values, k_values)


def _wide_context_saturation_case() -> AttentionScoreCase:
    q_values = [127 if (index & 1) == 0 else -128 for index in range(HEAD_DIM)]
    k_values = []
    for token in range(CONTEXT_MAX):
        if token == 0:
            k_values.append([127 if (index & 1) == 0 else -128 for index in range(HEAD_DIM)])
        elif token == 1:
            k_values.append([-128 if (index & 1) == 0 else 127 for index in range(HEAD_DIM)])
        else:
            k_values.append([((index * 13 + token * 17) % 65) - 32 for index in range(HEAD_DIM)])
    return AttentionScoreCase("eight_token_saturation_and_mixed", q_values, k_values)


def _unequal_scale_case() -> AttentionScoreCase:
    q_values = [((index * 5 + 1) % 5) - 2 for index in range(HEAD_DIM)]
    k_values = [
        [((index * 3 + token * 2) % 5) - 2 for index in range(HEAD_DIM)]
        for token in range(4)
    ]
    return AttentionScoreCase(
        "unequal_qk_scales_dynamic_requantization",
        q_values,
        k_values,
        query_scale=0.75,
        key_scale=1.25,
    )


def _cases() -> list[AttentionScoreCase]:
    return [
        _identity_like_case(),
        _rounding_tie_case(),
        _wide_context_saturation_case(),
        _unequal_scale_case(),
    ]


def _hex(value: int, width_bits: int) -> str:
    return f"{width_bits}'h{value & ((1 << width_bits) - 1):0{width_bits // 4}x}"


def _chunks(values: list[int], chunk_size: int) -> list[list[int]]:
    return [values[index : index + chunk_size] for index in range(0, len(values), chunk_size)]


def _digest_int8(values: list[int]) -> str:
    return hashlib.sha256(bytes(value & 0xFF for value in values)).hexdigest()


def _digest_int16(values: list[int]) -> str:
    return hashlib.sha256(b"".join((value & 0xFFFF).to_bytes(2, "little") for value in values)).hexdigest()


def main() -> None:
    OUT_SVH.parent.mkdir(parents=True, exist_ok=True)
    cases = _cases()
    records = []
    sv_lines = [
        "// Generated by tools/gen_attention_score_vectors.py; do not edit by hand.",
        f"localparam integer ATTN_SCORE_CASE_COUNT = {len(cases)};",
        f"localparam integer ATTN_SCORE_HEAD_DIM = {HEAD_DIM};",
        f"localparam integer ATTN_SCORE_MAC_LANES = {MAC_LANES};",
        f"localparam integer ATTN_SCORE_CONTEXT_MAX = {CONTEXT_MAX};",
        f"localparam integer ATTN_SCORE_BEATS_PER_VECTOR = {BEATS_PER_VECTOR};",
        "localparam [127:0] ATTN_SCORE_INVALID_NEGATIVE_MULTIPLIER = 128'h00000000000000000000000080000001;",
        "localparam [127:0] ATTN_SCORE_INVALID_RESERVED_BITS = 128'h80000000000000000000000000000001;",
        "reg [15:0] attn_score_context_count [0:ATTN_SCORE_CASE_COUNT-1];",
        "reg signed [31:0] attn_score_multiplier [0:ATTN_SCORE_CASE_COUNT-1];",
        "reg [5:0] attn_score_right_shift [0:ATTN_SCORE_CASE_COUNT-1];",
        "reg attn_score_expected_saturation [0:ATTN_SCORE_CASE_COUNT-1];",
        "reg attn_score_expected_saturation_token [0:ATTN_SCORE_CASE_COUNT*ATTN_SCORE_CONTEXT_MAX-1];",
        "reg attn_score_expected_core_saturation_token [0:ATTN_SCORE_CASE_COUNT*ATTN_SCORE_CONTEXT_MAX-1];",
        "reg [31:0] attn_score_expected_acc [0:ATTN_SCORE_CASE_COUNT*ATTN_SCORE_CONTEXT_MAX-1];",
        "reg [16*8-1:0] attn_score_expected_word [0:ATTN_SCORE_CASE_COUNT-1];",
        "reg [16*8-1:0] attn_score_expected_core_word [0:ATTN_SCORE_CASE_COUNT-1];",
        "reg [8*16-1:0] attn_score_q_beats [0:ATTN_SCORE_CASE_COUNT*ATTN_SCORE_BEATS_PER_VECTOR-1];",
        "reg [8*16-1:0] attn_score_k_beats [0:ATTN_SCORE_CASE_COUNT*ATTN_SCORE_CONTEXT_MAX*ATTN_SCORE_BEATS_PER_VECTOR-1];",
        "initial begin",
    ]

    for case_index, case in enumerate(cases):
        result = reference_attention_score(case)
        query_head = case_index
        metadata_word = pack_score_metadata(
            result.multiplier,
            result.right_shift,
            query_head=query_head,
        )
        padded_scores = result.scores_q6_9 + [0 for _ in range(CONTEXT_MAX - len(result.scores_q6_9))]
        padded_core_scores = result.core_scores_q6_9 + [
            0 for _ in range(CONTEXT_MAX - len(result.core_scores_q6_9))
        ]
        sv_lines.append(f"  // attention score case {case_index}: {case.name}")
        sv_lines.append(f"  attn_score_context_count[{case_index}] = 16'd{len(case.k_values)};")
        sv_lines.append(
            f"  attn_score_multiplier[{case_index}] = 32'sd{result.multiplier};"
        )
        sv_lines.append(
            f"  attn_score_right_shift[{case_index}] = 6'd{result.right_shift};"
        )
        sv_lines.append(f"  attn_score_expected_saturation[{case_index}] = 1'b{1 if result.saturation_seen else 0};")
        sv_lines.append(f"  attn_score_expected_word[{case_index}] = {_hex(pack_int16(padded_scores), 128)};")
        sv_lines.append(
            f"  attn_score_expected_core_word[{case_index}] = "
            f"{_hex(pack_int16(padded_core_scores), 128)};"
        )
        for beat_index, chunk in enumerate(_chunks(case.q_values, 16)):
            flat = case_index * BEATS_PER_VECTOR + beat_index
            sv_lines.append(f"  attn_score_q_beats[{flat}] = {_hex(pack_int8(chunk), 128)};")
        for token_index in range(CONTEXT_MAX):
            if token_index < len(case.k_values):
                k_vector = case.k_values[token_index]
                acc = result.accumulators[token_index]
                saturated = result.saturation_by_token[token_index]
                core_saturated = result.core_saturation_by_token[token_index]
            else:
                k_vector = [0 for _ in range(HEAD_DIM)]
                acc = 0
                saturated = False
                core_saturated = False
            flat_token = case_index * CONTEXT_MAX + token_index
            sv_lines.append(f"  attn_score_expected_acc[{flat_token}] = 32'h{acc & 0xFFFFFFFF:08x};")
            sv_lines.append(f"  attn_score_expected_saturation_token[{flat_token}] = 1'b{1 if saturated else 0};")
            sv_lines.append(
                f"  attn_score_expected_core_saturation_token[{flat_token}] = "
                f"1'b{1 if core_saturated else 0};"
            )
            for beat_index, chunk in enumerate(_chunks(k_vector, 16)):
                flat = (case_index * CONTEXT_MAX + token_index) * BEATS_PER_VECTOR + beat_index
                sv_lines.append(f"  attn_score_k_beats[{flat}] = {_hex(pack_int8(chunk), 128)};")
        records.append(
            {
                "name": case.name,
                "query_head": query_head,
                "context_count": len(case.k_values),
                "key_scale": case.key_scale,
                "multiplier": result.multiplier,
                "metadata_hex": f"{metadata_word:032x}",
                "query_scale": case.query_scale,
                "right_shift": result.right_shift,
                "saturation_seen": result.saturation_seen,
                "q_sha256": _digest_int8(case.q_values),
                "k_sha256": _digest_int8([value for vector in case.k_values for value in vector]),
                "score_sha256": _digest_int16(result.scores_q6_9),
                "core_score_sha256": _digest_int16(result.core_scores_q6_9),
            }
        )

    sv_lines.append("end")
    OUT_SVH.write_text("\n".join(sv_lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(
        json.dumps(
            {
                "schema_version": 2,
                "generator": "tools/gen_attention_score_vectors.py",
                "reference": "tools/ace2_attention_score_reference.py",
                "head_dim": HEAD_DIM,
                "mac_lanes": MAC_LANES,
                "context_max": CONTEXT_MAX,
                "beats_per_vector": BEATS_PER_VECTOR,
                "metadata_format": {
                    "rope_conversion": "bits_15_0_positive_signed_int16_Q6.9",
                    "multiplier": "bits_47_16_positive_signed_int32",
                    "right_shift": "bits_53_48_unsigned_0_to_63",
                    "mapped_kv_head": "bit_54_equals_floor_query_head_divided_by_7",
                    "query_head": "bits_58_55_equal_record_index_0_to_13",
                    "reserved": "bits_127_59_zero",
                },
                "invalid_metadata_cases": [
                    {
                        "expected_error": "numeric_overflow",
                        "expected_output_writes": 0,
                        "name": "negative_multiplier",
                    },
                    {
                        "expected_error": "numeric_overflow",
                        "expected_output_writes": 0,
                        "name": "nonzero_reserved_bits",
                    },
                    {"expected_error": "numeric_overflow", "expected_output_writes": 0, "name": "zero_conversion"},
                    {"expected_error": "numeric_overflow", "expected_output_writes": 0, "name": "query_head_id_mismatch"},
                    {"expected_error": "numeric_overflow", "expected_output_writes": 0, "name": "kv_head_mapping_mismatch"},
                    {"expected_error": "numeric_overflow", "expected_output_writes": 0, "name": "zero_multiplier"},
                ],
                "cases": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
