#!/usr/bin/env python3
"""Generate focused tile-max delta vectors from the independent oracle."""

from __future__ import annotations

import json
from pathlib import Path

from ace2_tile_max_delta_reference import (
    DELTA_SENTINEL,
    encode_score_row_from_numerators,
    softmax_q15_from_q6_17,
)


ROOT = Path(__file__).resolve().parents[1]
JSON_OUT = ROOT / "verification/generated/tile_max_delta_attention_vectors.json"
SVH_OUT = ROOT / "verification/generated/tile_max_delta_attention_vectors.svh"


def signed_literal(width: int, value: int) -> str:
    return f"-{width}'sd{-value}" if value < 0 else f"{width}'sd{value}"


def main() -> None:
    real_unit = 1 << 66
    rows = [
        [1000 * real_unit, 999 * real_unit, 998 * real_unit],
        [0] * 64 + [8 * real_unit, -40 * real_unit],
        [5 * real_unit, 5 * real_unit, 4 * real_unit, -20 * real_unit],
    ]
    cases = []
    for numerators in rows:
        deltas = encode_score_row_from_numerators(numerators)
        probabilities = softmax_q15_from_q6_17(deltas)
        cases.append({
            "numerators_s106": numerators,
            "deltas_q6_17_s24": deltas,
            "probabilities_q0_15": probabilities,
        })
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(
        json.dumps({
            "contract_id": "layer0_tile_max_delta_attention_v1",
            "delta_sentinel": DELTA_SENTINEL,
            "cases": cases,
        }, indent=2) + "\n",
        encoding="utf-8",
    )
    first = cases[0]
    lines = [
        "// Generated by tools/gen_tile_max_delta_attention_vectors.py; do not edit.",
        f"localparam signed [105:0] TILE_MAX_SCORE0 = {signed_literal(106, first['numerators_s106'][0])};",
        f"localparam signed [105:0] TILE_MAX_SCORE1 = {signed_literal(106, first['numerators_s106'][1])};",
        f"localparam signed [105:0] TILE_MAX_SCORE2 = {signed_literal(106, first['numerators_s106'][2])};",
        f"localparam signed [23:0] TILE_MAX_DELTA0 = {signed_literal(24, first['deltas_q6_17_s24'][0])};",
        f"localparam signed [23:0] TILE_MAX_DELTA1 = {signed_literal(24, first['deltas_q6_17_s24'][1])};",
        f"localparam signed [23:0] TILE_MAX_DELTA2 = {signed_literal(24, first['deltas_q6_17_s24'][2])};",
    ]
    SVH_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        "ACE2_TILE_MAX_DELTA_VECTORS_PASS "
        f"cases={len(cases)} sentinel={DELTA_SENTINEL}"
    )


if __name__ == "__main__":
    main()
