#!/usr/bin/env python3
"""Generate focused tile-BFP vectors from the independent oracle."""

from __future__ import annotations

import json
from pathlib import Path

from ace2_tile_bfp_reference import encode_score_row_from_numerators, encode_tile


ROOT = Path(__file__).resolve().parents[1]
JSON_OUT = ROOT / "verification/generated/tile_bfp_attention_vectors.json"
SVH_OUT = ROOT / "verification/generated/tile_bfp_attention_vectors.svh"


def signed_literal(width: int, value: int) -> str:
    return f"-{width}'sd{-value}" if value < 0 else f"{width}'sd{value}"


def main() -> None:
    real_unit = 1 << 66
    rows = [
        [1000 * real_unit, 999 * real_unit, 998 * real_unit],
        [0, -(64 * real_unit)],
        [0, -(1 << 48), -(3 << 48)],
    ]
    cases = []
    for numerators in rows:
        tile = encode_tile(numerators)
        cases.append({
            "numerators_s106": numerators,
            "tile_max_s128": tile.tile_max_s128,
            "tile_min_s128": tile.tile_min_s128,
            "fraction_bits_u5": tile.fraction_bits_u5,
            "mantissas_s24": tile.mantissas_s24,
            "reconstructed_q17_s32": encode_score_row_from_numerators(numerators),
        })
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(
        json.dumps({
            "contract_id": "layer0_tile_bfp_score_attention_v1",
            "cases": cases,
        }, indent=2) + "\n",
        encoding="utf-8",
    )
    first, boundary, ties = cases
    lines = [
        "// Generated by tools/gen_tile_bfp_attention_vectors.py; do not edit.",
        f"localparam signed [105:0] BFP_SCORE0 = {signed_literal(106, first['numerators_s106'][0])};",
        f"localparam signed [105:0] BFP_SCORE1 = {signed_literal(106, first['numerators_s106'][1])};",
        f"localparam signed [105:0] BFP_SCORE2 = {signed_literal(106, first['numerators_s106'][2])};",
        f"localparam [4:0] BFP_FRAC = 5'd{first['fraction_bits_u5']};",
        f"localparam signed [23:0] BFP_MANT0 = {signed_literal(24, first['mantissas_s24'][0])};",
        f"localparam signed [23:0] BFP_MANT1 = {signed_literal(24, first['mantissas_s24'][1])};",
        f"localparam signed [23:0] BFP_MANT2 = {signed_literal(24, first['mantissas_s24'][2])};",
        f"localparam signed [105:0] BFP_BOUNDARY_SCORE0 = {signed_literal(106, boundary['numerators_s106'][0])};",
        f"localparam signed [105:0] BFP_BOUNDARY_SCORE1 = {signed_literal(106, boundary['numerators_s106'][1])};",
        f"localparam [4:0] BFP_BOUNDARY_FRAC = 5'd{boundary['fraction_bits_u5']};",
        f"localparam signed [23:0] BFP_BOUNDARY_MANT1 = {signed_literal(24, boundary['mantissas_s24'][1])};",
        f"localparam signed [105:0] BFP_TIE_SCORE0 = {signed_literal(106, ties['numerators_s106'][0])};",
        f"localparam signed [105:0] BFP_TIE_SCORE1 = {signed_literal(106, ties['numerators_s106'][1])};",
        f"localparam signed [105:0] BFP_TIE_SCORE2 = {signed_literal(106, ties['numerators_s106'][2])};",
        f"localparam signed [23:0] BFP_TIE_MANT1 = {signed_literal(24, ties['mantissas_s24'][1])};",
        f"localparam signed [23:0] BFP_TIE_MANT2 = {signed_literal(24, ties['mantissas_s24'][2])};",
    ]
    SVH_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        "ACE2_TILE_BFP_VECTORS_PASS "
        f"cases={len(cases)} fractions={[case['fraction_bits_u5'] for case in cases]}"
    )


if __name__ == "__main__":
    main()
