#!/usr/bin/env python3
"""Generate ACE-2 attention-value RTL vectors from the Python reference."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from ace2_attention_value_reference import (
    CONTEXT_MAX,
    HEAD_DIM,
    AttentionValueCase,
    reference_attention_value,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "attention_value_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "attention_value_vectors.json"
BEATS_PER_VECTOR = HEAD_DIM // 16


def _ramp(offset: int, step: int) -> list[int]:
    return [((offset + lane * step + 128) % 256) - 128 for lane in range(HEAD_DIM)]


def _cases() -> list[AttentionValueCase]:
    return [
        AttentionValueCase("single_token_identity", [32768], [_ramp(-128, 5)]),
        AttentionValueCase(
            "two_token_ties_to_even",
            [16384, 16384],
            [
                [(-16 + lane) for lane in range(HEAD_DIM)],
                [(-15 + lane) for lane in range(HEAD_DIM)],
            ],
        ),
        AttentionValueCase(
            "eight_token_mixed",
            [8192, 6144, 5120, 4096, 3072, 2560, 2048, 1536],
            [_ramp(-91 + token * 17, 3 + token) for token in range(CONTEXT_MAX)],
        ),
        AttentionValueCase(
            "positive_saturation",
            [65535, 65535],
            [[127 for _ in range(HEAD_DIM)], [127 for _ in range(HEAD_DIM)]],
        ),
        AttentionValueCase(
            "negative_saturation",
            [65535, 65535],
            [[-128 for _ in range(HEAD_DIM)], [-128 for _ in range(HEAD_DIM)]],
        ),
    ]


def _pack(values: list[int], width: int) -> int:
    packed = 0
    mask = (1 << width) - 1
    for lane, value in enumerate(values):
        packed |= (value & mask) << (lane * width)
    return packed


def _hex(value: int, width_bits: int) -> str:
    return f"{width_bits}'h{value & ((1 << width_bits) - 1):0{width_bits // 4}x}"


def _digest(values: list[int], width: int) -> str:
    byte_width = width // 8
    return hashlib.sha256(
        b"".join((value & ((1 << width) - 1)).to_bytes(byte_width, "little") for value in values)
    ).hexdigest()


def main() -> None:
    OUT_SVH.parent.mkdir(parents=True, exist_ok=True)
    cases = _cases()
    records = []
    sv_lines = [
        "// Generated by tools/gen_attention_value_vectors.py; do not edit by hand.",
        f"localparam integer ATTN_VALUE_CASE_COUNT = {len(cases)};",
        f"localparam integer ATTN_VALUE_CONTEXT_MAX = {CONTEXT_MAX};",
        f"localparam integer ATTN_VALUE_HEAD_DIM = {HEAD_DIM};",
        f"localparam integer ATTN_VALUE_BEATS_PER_VECTOR = {BEATS_PER_VECTOR};",
        "reg [15:0] attn_value_context_count [0:ATTN_VALUE_CASE_COUNT-1];",
        "reg [16*8-1:0] attn_value_probability_word [0:ATTN_VALUE_CASE_COUNT-1];",
        "reg [127:0] attn_value_v_beats [0:ATTN_VALUE_CASE_COUNT*ATTN_VALUE_CONTEXT_MAX*ATTN_VALUE_BEATS_PER_VECTOR-1];",
        "reg [127:0] attn_value_expected_beats [0:ATTN_VALUE_CASE_COUNT*ATTN_VALUE_BEATS_PER_VECTOR-1];",
        "reg attn_value_expected_saturation [0:ATTN_VALUE_CASE_COUNT-1];",
        "initial begin",
    ]

    for case_index, case in enumerate(cases):
        result = reference_attention_value(case)
        padded_probabilities = case.probabilities_q15 + [0] * (CONTEXT_MAX - len(case.probabilities_q15))
        padded_values = case.values + [[0] * HEAD_DIM for _ in range(CONTEXT_MAX - len(case.values))]
        sv_lines.append(f"  // attention-value case {case_index}: {case.name}")
        sv_lines.append(f"  attn_value_context_count[{case_index}] = 16'd{len(case.probabilities_q15)};")
        sv_lines.append(
            f"  attn_value_probability_word[{case_index}] = "
            f"{_hex(_pack(padded_probabilities, 16), 128)};"
        )
        for token, row in enumerate(padded_values):
            for beat in range(BEATS_PER_VECTOR):
                flat_index = (
                    case_index * CONTEXT_MAX * BEATS_PER_VECTOR
                    + token * BEATS_PER_VECTOR
                    + beat
                )
                word = _pack(row[beat * 16 : (beat + 1) * 16], 8)
                sv_lines.append(f"  attn_value_v_beats[{flat_index}] = {_hex(word, 128)};")
        for beat in range(BEATS_PER_VECTOR):
            flat_index = case_index * BEATS_PER_VECTOR + beat
            word = _pack(result.outputs[beat * 16 : (beat + 1) * 16], 8)
            sv_lines.append(f"  attn_value_expected_beats[{flat_index}] = {_hex(word, 128)};")
        sv_lines.append(
            f"  attn_value_expected_saturation[{case_index}] = "
            f"1'b{int(result.saturation_seen)};"
        )
        records.append(
            {
                "name": case.name,
                "context_count": len(case.probabilities_q15),
                "probability_sha256": _digest(case.probabilities_q15, 16),
                "value_sha256": _digest([value for row in case.values for value in row], 8),
                "accumulator_sha256": _digest(result.accumulators, 32),
                "output_sha256": _digest(result.outputs, 8),
                "saturation_seen": result.saturation_seen,
            }
        )

    sv_lines.append("end")
    OUT_SVH.write_text("\n".join(sv_lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "generator": "tools/gen_attention_value_vectors.py",
                "reference": "tools/ace2_attention_value_reference.py",
                "context_max": CONTEXT_MAX,
                "head_dim": HEAD_DIM,
                "probability_format": "unsigned_int16 Q0.15",
                "value_format": "signed_int8",
                "accumulator_format": "signed_int32",
                "output_format": "signed_int8",
                "rounding": "round_to_nearest_ties_to_even_after_15_fractional_bits",
                "cases": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
