#!/usr/bin/env python3
"""Generate deterministic JSON/SVH vectors for V-residual RTL."""

from __future__ import annotations

import json
from pathlib import Path

try:
    from ace2_v_residual_value_correction_reference import (
        canonical_s4_byte,
        kv_head_for_query_head,
        v_projection_residual,
        v_residual_value_correction,
    )
except ModuleNotFoundError:
    from tools.ace2_v_residual_value_correction_reference import (
        canonical_s4_byte,
        kv_head_for_query_head,
        v_projection_residual,
        v_residual_value_correction,
    )


ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "verification/generated/v_residual_value_correction_vectors.json"
OUT_SVH = ROOT / "verification/generated/v_residual_value_correction_vectors.svh"
SCALE_ONE = 0x00008000
SCALE_HALF = 0x00FF8000


PROJECTION_INPUTS = [
    (3, 5, 1, SCALE_ONE, SCALE_HALF),
    (-17, 257, 5, SCALE_HALF, SCALE_ONE),
    (1000, 4096, 12, SCALE_ONE, 0x00F88000),
    (-1000, 4096, 12, SCALE_ONE, 0x00F88000),
]


def correction_case(length: int, seed: int) -> dict[str, object]:
    probabilities = [((index * (7919 + seed)) + 4096) & 0xFFFF for index in range(length)]
    residuals = [((index * (5 + seed)) % 15) - 7 for index in range(length)]
    residual_bytes = [canonical_s4_byte(value) for value in residuals]
    baseline_accumulator = (seed + 3) * 1000 - 1700
    result = v_residual_value_correction(
        probabilities,
        residual_bytes,
        SCALE_ONE,
        SCALE_HALF,
        baseline_accumulator,
    )
    return {
        "row_length": length,
        "probabilities_q0_15": probabilities,
        "residual_v_s4": residuals,
        "residual_v_canonical_u8": residual_bytes,
        "baseline_v_scale32": SCALE_ONE,
        "residual_v_scale32": SCALE_HALF,
        "authoritative_baseline_accumulator_s32": baseline_accumulator,
        "correction_raw_s64": result.correction_raw_s64,
        "correction_baseline_domain_s32": result.correction_baseline_domain_s32,
        "corrected_accumulator_s32": result.corrected_accumulator_s32,
    }


def sv_signed(width: int, value: int) -> str:
    return f"-{width}'sd{abs(value)}" if value < 0 else f"{width}'sd{value}"


def main() -> int:
    projection_cases = []
    for values in PROJECTION_INPUTS:
        result = v_projection_residual(*values)
        projection_cases.append(
            {
                "input": {
                    "accumulator_s32": values[0],
                    "multiplier_s32": values[1],
                    "shift_u6": values[2],
                    "baseline_v_scale32": values[3],
                    "residual_v_scale32": values[4],
                },
                "expected": {
                    "baseline_v8": result.baseline_v8,
                    "residual_v_s4": result.residual_v_s4,
                    "residual_v_canonical_u8": result.residual_v_canonical_u8,
                    "positive_clamp": result.positive_clamp,
                    "negative_clamp": result.negative_clamp,
                },
            }
        )
    correction_cases = [correction_case(length, index) for index, length in enumerate((1, 2, 5, 63, 64, 65))]
    payload = {
        "schema_version": 1,
        "contract_id": "shared_v_residual_value_correction_attention_v1",
        "coverage": {
            "layer_ids": list(range(24)),
            "query_to_kv_head": [kv_head_for_query_head(head) for head in range(14)],
            "row_lengths": [1, 2, 5, 63, 64, 65],
            "reserved_s4_code": -8,
            "conversion_cycles": 8,
            "baseline_boundaries_preserved": [
                "q_projection",
                "k_projection",
                "v_projection",
                "rope",
                "score",
                "softmax_probability",
            ],
        },
        "projection_cases": projection_cases,
        "correction_cases": correction_cases,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = ["// Generated by tools/gen_v_residual_value_correction_vectors.py"]
    for index, case in enumerate(projection_cases):
        inputs = case["input"]
        expected = case["expected"]
        lines.extend(
            [
                f"localparam logic signed [31:0] VRP_{index}_ACC = {sv_signed(32, inputs['accumulator_s32'])};",
                f"localparam logic signed [31:0] VRP_{index}_MUL = {sv_signed(32, inputs['multiplier_s32'])};",
                f"localparam logic [5:0] VRP_{index}_SHIFT = 6'd{inputs['shift_u6']};",
                f"localparam logic [31:0] VRP_{index}_BASE_SCALE = 32'h{inputs['baseline_v_scale32']:08x};",
                f"localparam logic [31:0] VRP_{index}_RES_SCALE = 32'h{inputs['residual_v_scale32']:08x};",
                f"localparam logic signed [7:0] VRP_{index}_BASE_V8 = {sv_signed(8, expected['baseline_v8'])};",
                f"localparam logic [7:0] VRP_{index}_RESIDUAL_U8 = 8'h{expected['residual_v_canonical_u8']:02x};",
                f"localparam logic VRP_{index}_POS_CLAMP = 1'b{int(expected['positive_clamp'])};",
                f"localparam logic VRP_{index}_NEG_CLAMP = 1'b{int(expected['negative_clamp'])};",
            ]
        )
    case = correction_cases[2]
    lines.extend(
        [
            f"localparam logic [15:0] VRC_LANE_COUNT = 16'd{case['row_length']};",
            f"localparam logic signed [31:0] VRC_BASE_ACC = {sv_signed(32, case['authoritative_baseline_accumulator_s32'])};",
            f"localparam logic [31:0] VRC_BASE_SCALE = 32'h{case['baseline_v_scale32']:08x};",
            f"localparam logic [31:0] VRC_RES_SCALE = 32'h{case['residual_v_scale32']:08x};",
            f"localparam logic signed [63:0] VRC_CORR_RAW = {sv_signed(64, case['correction_raw_s64'])};",
            f"localparam logic signed [31:0] VRC_CORR = {sv_signed(32, case['correction_baseline_domain_s32'])};",
            f"localparam logic signed [31:0] VRC_RESULT = {sv_signed(32, case['corrected_accumulator_s32'])};",
        ]
    )
    for index, (probability, residual_byte) in enumerate(
        zip(case["probabilities_q0_15"], case["residual_v_canonical_u8"], strict=True)
    ):
        lines.extend(
            [
                f"localparam logic [15:0] VRC_P_{index} = 16'd{probability};",
                f"localparam logic [7:0] VRC_R_{index} = 8'h{residual_byte:02x};",
            ]
        )
    OUT_SVH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {OUT_JSON.relative_to(ROOT)} and {OUT_SVH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
