#!/usr/bin/env python3
"""Generate deterministic focused vectors and the Q1.31 exp RTL table."""

from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path

from ace2_absolute_rope_online_attention_reference import (
    K_SCALE32,
    Q_SCALE32,
    OnlineAttentionState,
    absolute_coefficients_q15,
    absolute_rope_score_raw,
    exp_q31,
    exp_table_q31,
    finalize_online_state,
    score_raw_to_logit_q12_20,
    update_online_state,
)


ROOT = Path(__file__).resolve().parents[1]
JSON_OUT = ROOT / "verification/generated/absolute_rope_online_attention_vectors.json"
SVH_OUT = ROOT / "verification/generated/absolute_rope_online_attention_vectors.svh"
LUT_OUT = ROOT / "rtl/generated/ace2_exp_q31_lut.svh"


def hex_packed(values: list[int] | tuple[int, ...], width: int) -> str:
    mask = (1 << width) - 1
    packed = 0
    for index, value in enumerate(values):
        packed |= (int(value) & mask) << (index * width)
    return f"{len(values) * width}'h{packed:0{(len(values) * width + 3) // 4}x}"


def signed_literal(value: int, width: int) -> str:
    return f"-{width}'sd{-value}" if value < 0 else f"{width}'sd{value}"


def main() -> None:
    rng = random.Random(0xACE2A801)
    query = [rng.randrange(-128, 128) for _ in range(64)]
    keys = [[rng.randrange(-128, 128) for _ in range(64)] for _ in range(3)]
    values = [[rng.randrange(-128, 128) for _ in range(64)] for _ in range(3)]
    query_position = 2
    q_cos, q_sin = absolute_coefficients_q15(query_position)

    score_cases = []
    state = OnlineAttentionState()
    update_cases = []
    for key_position, (key, value) in enumerate(zip(keys, values, strict=True)):
        k_cos, k_sin = absolute_coefficients_q15(key_position)
        score_raw, rotated_query, rotated_key = absolute_rope_score_raw(
            query, key, query_position, key_position
        )
        logit = score_raw_to_logit_q12_20(score_raw)
        score_cases.append(
            {
                "key_position": key_position,
                "query": query,
                "key": key,
                "query_cos": q_cos,
                "query_sin": q_sin,
                "key_cos": k_cos,
                "key_sin": k_sin,
                "rotated_query": rotated_query,
                "rotated_key": rotated_key,
                "score_raw": score_raw,
                "logit_q12_20": logit,
            }
        )
        before = state
        state = update_online_state(state, logit, value)
        update_cases.append(
            {
                "logit_q12_20": logit,
                "value": value,
                "state_valid_before": before.valid,
                "maximum_before": before.maximum or 0,
                "denominator_before": before.denominator,
                "numerators_before": before.numerators,
                "maximum_after": state.maximum,
                "denominator_after": state.denominator,
                "numerators_after": state.numerators,
            }
        )

    exp_deltas = [0, -1, -0x8000, -0x10000, -(15 << 20), -(16 << 20), -(17 << 20)]
    payload = {
        "schema_version": 1,
        "contract_id": "layer0_absolute_rope_online_attention_v1",
        "seed": "0xACE2A801",
        "query_scale32": Q_SCALE32,
        "key_scale32": K_SCALE32,
        "score_cases": score_cases,
        "update_cases": update_cases,
        "final_output": finalize_online_state(state),
        "exp_cases": [{"delta": delta, "weight": exp_q31(delta)} for delta in exp_deltas],
        "exp_table": exp_table_q31(),
    }
    JSON_OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    lines = [
        "// Generated by tools/gen_absolute_rope_online_attention_vectors.py",
        "localparam integer ABS_ROPE_SCORE_CASE_COUNT = 3;",
        "task automatic load_abs_rope_score_case;",
        "  input integer case_index;",
        "  output reg [511:0] case_query;",
        "  output reg [511:0] case_key;",
        "  output reg [511:0] case_query_cos;",
        "  output reg [511:0] case_query_sin;",
        "  output reg [511:0] case_key_cos;",
        "  output reg [511:0] case_key_sin;",
        "  output reg signed [53:0] case_score_raw;",
        "  output reg signed [63:0] case_logit;",
        "  begin",
        "    case_query = 512'd0; case_key = 512'd0;",
        "    case_query_cos = 512'd0; case_query_sin = 512'd0;",
        "    case_key_cos = 512'd0; case_key_sin = 512'd0;",
        "    case_score_raw = 54'sd0; case_logit = 64'sd0;",
        "    case (case_index)",
    ]
    for index, case in enumerate(score_cases):
        lines.extend(
            [
                f"      {index}: begin",
                f"        case_query = {hex_packed(case['query'], 8)};",
                f"        case_key = {hex_packed(case['key'], 8)};",
                f"        case_query_cos = {hex_packed(case['query_cos'], 16)};",
                f"        case_query_sin = {hex_packed(case['query_sin'], 16)};",
                f"        case_key_cos = {hex_packed(case['key_cos'], 16)};",
                f"        case_key_sin = {hex_packed(case['key_sin'], 16)};",
                f"        case_score_raw = {signed_literal(case['score_raw'], 54)};",
                f"        case_logit = {signed_literal(case['logit_q12_20'], 64)};",
                "      end",
            ]
        )
    lines.extend(["      default: begin end", "    endcase", "  end", "endtask", ""])
    SVH_OUT.write_text("\n".join(lines), encoding="utf-8")

    lut_lines = [
        "// Generated by tools/gen_absolute_rope_online_attention_vectors.py",
        "function automatic [31:0] ace2_exp_q31_lut;",
        "    input [8:0] index;",
        "    begin",
        "        case (index)",
    ]
    for index, value in enumerate(exp_table_q31()):
        lut_lines.append(f"            9'd{index}: ace2_exp_q31_lut = 32'h{value:08x};")
    lut_lines.extend(
        [
            "            default: ace2_exp_q31_lut = 32'd0;",
            "        endcase",
            "    end",
            "endfunction",
            "",
        ]
    )
    LUT_OUT.write_text("\n".join(lut_lines), encoding="utf-8")

    print(
        "ACE2_ABSOLUTE_ROPE_VECTORS_PASS "
        f"json_sha256={hashlib.sha256(JSON_OUT.read_bytes()).hexdigest()} "
        f"lut_sha256={hashlib.sha256(LUT_OUT.read_bytes()).hexdigest()}"
    )


if __name__ == "__main__":
    main()

