#!/usr/bin/env python3
"""Generate deterministic JSON/SVH vectors for tagged attention RTL."""

from __future__ import annotations

import json
from pathlib import Path

try:
    from ace2_native_accumulator_tagged_reference import (
        TaggedLane,
        tagged_rope_pair,
        tagged_score_q20_44,
    )
except ModuleNotFoundError:
    from tools.ace2_native_accumulator_tagged_reference import (
        TaggedLane,
        tagged_rope_pair,
        tagged_score_q20_44,
    )


ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "verification/generated/native_accumulator_tagged_attention_vectors.json"
OUT_SVH = ROOT / "verification/generated/native_accumulator_tagged_attention_vectors.svh"


ROPE_INPUTS = [
    (123456, 0x00FFA245, -234567, 0x00008307, 32767, 0),
    (-214748, 0x00F18000, 333333, 0x00F48000, 23170, 23170),
    (17, 0x00E88000, -19, 0x00E98000, -12540, 30274),
    (0, 0x00FFA245, 0, 0x00008307, 32767, 0),
]

SCORE_INPUTS = [
    (
        [(1 << 29, -20), (-(1 << 28), -19), (123456789, -18), (-98765432, -18)],
        [(-(1 << 29), -20), (1 << 28, -19), (234567890, -18), (76543210, -18)],
    ),
    (
        [(1073741823, -24), (-1073741823, -24)],
        [(1073741823, -24), (1073741823, -24)],
    ),
    (
        [(1, -30)] * 64,
        [(1, -30)] * 64,
    ),
]


def sv_signed(width: int, value: int) -> str:
    return f"-{width}'sd{abs(value)}" if value < 0 else f"{width}'sd{value}"


def main() -> int:
    rope = []
    for values in ROPE_INPUTS:
        result = tagged_rope_pair(*values)
        rope.append(
            {
                "input": {
                    "acc0": values[0],
                    "scale0": values[1],
                    "acc1": values[2],
                    "scale1": values[3],
                    "cosine_q15": values[4],
                    "sine_q15": values[5],
                },
                "expected": {
                    "real_mantissa": result.real.mantissa,
                    "real_exponent": result.real.exponent,
                    "imag_mantissa": result.imag.mantissa,
                    "imag_exponent": result.imag.exponent,
                },
            }
        )
    scores = []
    for query, key in SCORE_INPUTS:
        result = tagged_score_q20_44(
            [TaggedLane(*item) for item in query],
            [TaggedLane(*item) for item in key],
        )
        scores.append({"query": query, "key": key, "expected_score_q20_44": result})

    payload = {"schema_version": 1, "rope_cases": rope, "score_cases": scores}
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

    lines = ["// Generated by tools/gen_native_accumulator_tagged_vectors.py"]
    lines.append(f"localparam int NAT_ROPE_CASES = {len(rope)};")
    for index, case in enumerate(rope):
        i = case["input"]
        e = case["expected"]
        lines.extend(
            [
                f"localparam logic signed [31:0] NAT_R{index}_ACC0 = {sv_signed(32, i['acc0'])};",
                f"localparam logic [31:0] NAT_R{index}_SCALE0 = 32'h{i['scale0']:08x};",
                f"localparam logic signed [31:0] NAT_R{index}_ACC1 = {sv_signed(32, i['acc1'])};",
                f"localparam logic [31:0] NAT_R{index}_SCALE1 = 32'h{i['scale1']:08x};",
                f"localparam logic signed [15:0] NAT_R{index}_COS = {sv_signed(16, i['cosine_q15'])};",
                f"localparam logic signed [15:0] NAT_R{index}_SIN = {sv_signed(16, i['sine_q15'])};",
                f"localparam logic signed [31:0] NAT_R{index}_REAL_M = {sv_signed(32, e['real_mantissa'])};",
                f"localparam logic signed [7:0] NAT_R{index}_REAL_E = {sv_signed(8, e['real_exponent'])};",
                f"localparam logic signed [31:0] NAT_R{index}_IMAG_M = {sv_signed(32, e['imag_mantissa'])};",
                f"localparam logic signed [7:0] NAT_R{index}_IMAG_E = {sv_signed(8, e['imag_exponent'])};",
            ]
        )
    lines.append(f"localparam int NAT_SCORE_CASES = {len(scores)};")
    for case_index, case in enumerate(scores):
        lines.append(f"localparam int NAT_S{case_index}_LANES = {len(case['query'])};")
        lines.append(
            f"localparam logic signed [63:0] NAT_S{case_index}_EXPECTED = {sv_signed(64, case['expected_score_q20_44'])};"
        )
        for lane, ((qm, qe), (km, ke)) in enumerate(
            zip(case["query"], case["key"], strict=True)
        ):
            lines.extend(
                [
                    f"localparam logic signed [31:0] NAT_S{case_index}_Q_M_{lane} = {sv_signed(32, qm)};",
                    f"localparam logic signed [7:0] NAT_S{case_index}_Q_E_{lane} = {sv_signed(8, qe)};",
                    f"localparam logic signed [31:0] NAT_S{case_index}_K_M_{lane} = {sv_signed(32, km)};",
                    f"localparam logic signed [7:0] NAT_S{case_index}_K_E_{lane} = {sv_signed(8, ke)};",
                ]
            )
    OUT_SVH.write_text("\n".join(lines) + "\n")
    print(f"generated {OUT_JSON.relative_to(ROOT)} and {OUT_SVH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
