#!/usr/bin/env python3
"""Generate focused projection-shadow RTL vectors from the integer oracle."""

from __future__ import annotations

import json
import random
from pathlib import Path

from ace2_absolute_rope_online_attention_reference import absolute_coefficients_q15
from ace2_projection_shadow_reference import (
    K_SCALE32,
    Q_SCALE32,
    projection_shadow_q15_16,
    rotate_shadow_head,
    shadow_score_q6_9,
)


ROOT = Path(__file__).resolve().parents[1]
JSON_OUT = ROOT / "verification/generated/projection_shadow_vectors.json"
SVH_OUT = ROOT / "verification/generated/projection_shadow_vectors.svh"


def pack(values: list[int] | tuple[int, ...], width: int) -> int:
    result = 0
    mask = (1 << width) - 1
    for index, value in enumerate(values):
        result |= (int(value) & mask) << (index * width)
    return result


def sv_signed(width: int, value: int) -> str:
    return f"-{width}'sd{-value}" if value < 0 else f"{width}'sd{value}"


def main() -> None:
    projection_cases = [
        (3, 0, 1, 17),
        (5, 0, 1, 17),
        (-3, 0, 1, 17),
        (7, -2, 3, 14),
        (123456, -2345, 1_340_316_350, 42),
    ]
    projection = [
        {
            "dot": dot,
            "bias": bias,
            "multiplier": multiplier,
            "right_shift": shift,
            "shadow": projection_shadow_q15_16(dot, bias, multiplier, shift),
        }
        for dot, bias, multiplier, shift in projection_cases
    ]

    rng = random.Random(0xACE25015)
    score = []
    for query_position, key_position in ((0, 0), (3, 1), (63, 17)):
        query = [rng.randrange(-4_000_000, 4_000_001) for _ in range(64)]
        key = [rng.randrange(-4_000_000, 4_000_001) for _ in range(64)]
        qrot = rotate_shadow_head(query, query_position)
        krot = rotate_shadow_head(key, key_position)
        dot = sum(a * b for a, b in zip(qrot, krot, strict=True))
        qcos, qsin = absolute_coefficients_q15(query_position)
        kcos, ksin = absolute_coefficients_q15(key_position)
        score.append({
            "query": query,
            "key": key,
            "query_cos": qcos,
            "query_sin": qsin,
            "key_cos": kcos,
            "key_sin": ksin,
            "dot": dot,
            "score": shadow_score_q6_9(
                query, key, query_position, key_position, Q_SCALE32, K_SCALE32
            ),
        })

    JSON_OUT.write_text(json.dumps({
        "contract_id": "layer0_projection_shadow_staged_attention_v1",
        "projection_cases": projection,
        "score_cases": score,
    }, indent=2) + "\n", encoding="utf-8")

    lines = [
        "// Generated by tools/gen_projection_shadow_vectors.py; do not edit.",
        f"localparam integer PROJECTION_SHADOW_CASE_COUNT = {len(projection)};",
        f"localparam integer PROJECTION_SHADOW_SCORE_CASE_COUNT = {len(score)};",
        "task load_projection_shadow_case;",
        "  input integer index;",
        "  output reg signed [31:0] dot;",
        "  output reg signed [31:0] bias;",
        "  output reg signed [31:0] multiplier;",
        "  output reg [5:0] shift;",
        "  output reg signed [31:0] expected;",
        "  begin",
        "    case (index)",
    ]
    for index, case in enumerate(projection):
        lines.append(
            f"      {index}: begin dot={sv_signed(32, case['dot'])}; "
            f"bias={sv_signed(32, case['bias'])}; "
            f"multiplier={sv_signed(32, case['multiplier'])}; "
            f"shift=6'd{case['right_shift']}; "
            f"expected={sv_signed(32, case['shadow'])}; end"
        )
    lines += [
        "      default: begin dot=0; bias=0; multiplier=1; shift=16; expected=0; end",
        "    endcase",
        "  end",
        "endtask",
        "task load_projection_shadow_score_case;",
        "  input integer index;",
        "  output reg [2047:0] query;",
        "  output reg [2047:0] key;",
        "  output reg [511:0] query_cos;",
        "  output reg [511:0] query_sin;",
        "  output reg [511:0] key_cos;",
        "  output reg [511:0] key_sin;",
        "  output reg signed [73:0] expected_dot;",
        "  output reg signed [15:0] expected_score;",
        "  begin",
        "    case (index)",
    ]
    for index, case in enumerate(score):
        lines += [
            f"      {index}: begin",
            f"        query=2048'h{pack(case['query'], 32):0512x};",
            f"        key=2048'h{pack(case['key'], 32):0512x};",
            f"        query_cos=512'h{pack(case['query_cos'], 16):0128x};",
            f"        query_sin=512'h{pack(case['query_sin'], 16):0128x};",
            f"        key_cos=512'h{pack(case['key_cos'], 16):0128x};",
            f"        key_sin=512'h{pack(case['key_sin'], 16):0128x};",
            f"        expected_dot={sv_signed(74, case['dot'])}; "
            f"expected_score={sv_signed(16, case['score'])};",
            "      end",
        ]
    lines += [
        "      default: begin query=0; key=0; query_cos=0; query_sin=0; key_cos=0; key_sin=0; expected_dot=0; expected_score=0; end",
        "    endcase",
        "  end",
        "endtask",
    ]
    SVH_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        "ACE2_PROJECTION_SHADOW_VECTORS_PASS "
        f"projection_cases={len(projection)} score_cases={len(score)}"
    )


if __name__ == "__main__":
    main()
