#!/usr/bin/env python3
"""Generate distinct post-attention RMSNorm vectors using the RMSNorm oracle."""

from __future__ import annotations

import hashlib
import json
import random
import struct
from pathlib import Path

from ace2_rmsnorm_reference import (
    BEATS,
    HIDDEN_SIZE,
    derive_scaled_gains_q8,
    pack_gain_beats,
    pack_int8_beats,
    reference_rmsnorm,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "post_attention_rmsnorm_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "post_attention_rmsnorm_vectors.json"


def _cases() -> list[tuple[str, list[int], list[float], float]]:
    unity = [1.0] * HIDDEN_SIZE
    cases = [
        ("residual_zero", [0] * HIDDEN_SIZE, unity, 3.0 / 128.0),
        (
            "residual_alternating",
            [96 if index & 1 else -96 for index in range(HIDDEN_SIZE)],
            unity,
            5.0 / 128.0,
        ),
    ]
    rng = random.Random(0xACE20213)
    random_scales = [1.0 / 32.0, 3.0 / 64.0, 1.0 / 64.0, 5.0 / 128.0]
    for case_index in range(4):
        activations = [rng.randint(-128, 127) for _ in range(HIDDEN_SIZE)]
        weights = [rng.uniform(0.8, 1.2) for _ in range(HIDDEN_SIZE)]
        cases.append(
            (
                f"post_attention_seeded_{case_index}",
                activations,
                weights,
                random_scales[case_index],
            )
        )
    return cases


def _hex(value: int, width: int) -> str:
    return f"{width}'h{value & ((1 << width) - 1):0{width // 4}x}"


def main() -> None:
    cases = _cases()
    records = []
    lines = [
        "// Generated by tools/gen_post_attention_rmsnorm_vectors.py; do not edit by hand.",
        f"localparam integer POST_RMS_CASE_COUNT = {len(cases)};",
        f"localparam integer POST_RMS_BEATS = {BEATS};",
        "reg [127:0] post_rms_input_beats [0:POST_RMS_CASE_COUNT*POST_RMS_BEATS-1];",
        "reg [255:0] post_rms_gain_beats [0:POST_RMS_CASE_COUNT*POST_RMS_BEATS-1];",
        "reg [127:0] post_rms_expected_beats [0:POST_RMS_CASE_COUNT*POST_RMS_BEATS-1];",
        "reg [47:0] post_rms_expected_sumsq [0:POST_RMS_CASE_COUNT-1];",
        "reg [31:0] post_rms_expected_inv [0:POST_RMS_CASE_COUNT-1];",
        "reg post_rms_expected_saturation [0:POST_RMS_CASE_COUNT-1];",
        "initial begin",
    ]
    for case_index, (name, activations, weights, output_scale) in enumerate(cases):
        gains = derive_scaled_gains_q8(weights, output_scale)
        result = reference_rmsnorm(activations, gains)
        input_beats = pack_int8_beats(activations)
        gain_beats = pack_gain_beats(gains)
        output_beats = pack_int8_beats(result.outputs)
        records.append({
            "name": name,
            "output_scale": output_scale,
            "input_sha256": hashlib.sha256(bytes(value & 0xFF for value in activations)).hexdigest(),
            "weight_sha256": hashlib.sha256(
                b"".join(struct.pack("<d", value) for value in weights)
            ).hexdigest(),
            "gain_sha256": hashlib.sha256(
                b"".join((value & 0xFFFF).to_bytes(2, "little") for value in gains)
            ).hexdigest(),
            "output_sha256": hashlib.sha256(bytes(value & 0xFF for value in result.outputs)).hexdigest(),
            "sumsq": result.sumsq,
            "inv_rms_q30": result.inv_rms_q30,
            "saturation_seen": result.saturation_seen,
        })
        lines.append(f"  post_rms_expected_sumsq[{case_index}] = {_hex(result.sumsq, 48)};")
        lines.append(f"  post_rms_expected_inv[{case_index}] = {_hex(result.inv_rms_q30, 32)};")
        lines.append(f"  post_rms_expected_saturation[{case_index}] = 1'b{int(result.saturation_seen)};")
        for beat_index in range(BEATS):
            flat = case_index * BEATS + beat_index
            lines.append(f"  post_rms_input_beats[{flat}] = {_hex(input_beats[beat_index], 128)};")
            lines.append(f"  post_rms_gain_beats[{flat}] = {_hex(gain_beats[beat_index], 256)};")
            lines.append(f"  post_rms_expected_beats[{flat}] = {_hex(output_beats[beat_index], 128)};")
    lines.append("end")
    OUT_SVH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(json.dumps({
        "schema_version": 2,
        "generator": "tools/gen_post_attention_rmsnorm_vectors.py",
        "reference": "tools/ace2_rmsnorm_reference.py",
        "operator": "layer_0.post_attention_rmsnorm",
        "hidden_size": HIDDEN_SIZE,
        "beats": BEATS,
        "output_format": {
            "storage": "signed_int8",
            "scale": "static_per_test_tensor",
            "scale_derivation": "calibrated_BF16_output_absmax_divided_by_127",
            "gain_metadata": "signed_int16_Q7.8_of_weight_divided_by_output_scale",
            "rounding": "nearest_ties_to_even",
            "saturation": [-128, 127],
        },
        "cases": records,
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
