#!/usr/bin/env python3
"""Generate ACE-2 RoPE RTL vectors from the Python reference."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from ace2_rope_reference import (
    HEAD_DIM,
    HIDDEN_SIZE,
    LANES,
    Q9_SCALE_ONE,
    Q15_ONE,
    ROPE_BEATS,
    RopeCase,
    pack_int8,
    pack_int16,
    reference_rope,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "rope_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "rope_vectors.json"


def _identity_case() -> RopeCase:
    activations = [((index * 9 + 5) % 7) - 3 for index in range(HIDDEN_SIZE)]
    scales = [Q9_SCALE_ONE for _ in range(HIDDEN_SIZE)]
    cos = [Q15_ONE for _ in range(HIDDEN_SIZE)]
    sin = [0 for _ in range(HIDDEN_SIZE)]
    return RopeCase("position0_identity", 0, activations, scales, cos, sin)


def _quarter_turn_case() -> RopeCase:
    activations = [((index * 7 + 19) % 7) - 3 for index in range(HIDDEN_SIZE)]
    scales = [Q9_SCALE_ONE for _ in range(HIDDEN_SIZE)]
    cos = [0 for _ in range(HIDDEN_SIZE)]
    sin = [Q15_ONE for _ in range(HIDDEN_SIZE)]
    return RopeCase("quarter_turn_split_half", 13, activations, scales, cos, sin)


def _mixed_case() -> RopeCase:
    activations = [((index * 23 + 11) % 31) - 15 for index in range(HIDDEN_SIZE)]
    scales = [
        Q9_SCALE_ONE + (((index // HEAD_DIM) % 5) - 2) * 64
        for index in range(HIDDEN_SIZE)
    ]
    cos: list[int] = []
    sin: list[int] = []
    for index in range(HIDDEN_SIZE):
        dim = index % HEAD_DIM
        selector = dim % 4
        if selector == 0:
            cos.append(30274)
            sin.append(12540)
        elif selector == 1:
            cos.append(23170)
            sin.append(23170)
        elif selector == 2:
            cos.append(12540)
            sin.append(30274)
        else:
            cos.append(Q15_ONE)
            sin.append(0)
    return RopeCase("mixed_q9_scales", 32767, activations, scales, cos, sin)


def _wide_q9_case() -> RopeCase:
    activations = [127 if (index & 3) == 0 else -128 if (index & 3) == 1 else ((index * 19) % 63) - 31 for index in range(HIDDEN_SIZE)]
    scales = [
        32767 - ((index // HEAD_DIM) % 5) * 2048
        for index in range(HIDDEN_SIZE)
    ]
    cos: list[int] = []
    sin: list[int] = []
    for index in range(HIDDEN_SIZE):
        if index & 1:
            cos.append(23170)
            sin.append(23170)
        else:
            cos.append(30274)
            sin.append(-12540)
    return RopeCase("wide_q9_pre_rotation_and_output_saturation", 8191, activations, scales, cos, sin)


def _range_safe_int8_extrema_case() -> RopeCase:
    activations: list[int] = []
    for index in range(HIDDEN_SIZE):
        dim = index % HEAD_DIM
        activations.append(127 if dim < 32 else -128)
    scales = [359 for _ in range(HIDDEN_SIZE)]
    cos = [23170 for _ in range(HIDDEN_SIZE)]
    sin = [23170 for _ in range(HIDDEN_SIZE)]
    return RopeCase(
        "range_safe_q9_359_signed_int8_extrema",
        31,
        activations,
        scales,
        cos,
        sin,
    )


def _cases() -> list[RopeCase]:
    return [
        _identity_case(),
        _quarter_turn_case(),
        _mixed_case(),
        _wide_q9_case(),
        _range_safe_int8_extrema_case(),
    ]


def _hex(value: int, width_bits: int) -> str:
    return f"{width_bits}'h{value & ((1 << width_bits) - 1):0{width_bits // 4}x}"


def _chunks(values: list[int], chunk_size: int) -> list[list[int]]:
    return [values[index : index + chunk_size] for index in range(0, len(values), chunk_size)]


def main() -> None:
    OUT_SVH.parent.mkdir(parents=True, exist_ok=True)
    cases = _cases()
    records = []
    sv_lines = [
        "// Generated by tools/gen_rope_vectors.py; do not edit by hand.",
        f"localparam integer ROPE_CASE_COUNT = {len(cases)};",
        f"localparam integer ROPE_HIDDEN_SIZE = {HIDDEN_SIZE};",
        f"localparam integer ROPE_LANES = {LANES};",
        f"localparam integer ROPE_BEATS = {ROPE_BEATS};",
        "reg [15:0] rope_sequence_position [0:ROPE_CASE_COUNT-1];",
        "reg rope_expected_saturation [0:ROPE_CASE_COUNT-1];",
        "reg [8*16-1:0] rope_input_beats [0:ROPE_CASE_COUNT*ROPE_BEATS-1];",
        "reg [16*8-1:0] rope_scale_beats [0:ROPE_CASE_COUNT*ROPE_BEATS*2-1];",
        "reg [16*8-1:0] rope_cos_beats [0:ROPE_CASE_COUNT*ROPE_BEATS*2-1];",
        "reg [16*8-1:0] rope_sin_beats [0:ROPE_CASE_COUNT*ROPE_BEATS*2-1];",
        "reg [8*16-1:0] rope_expected_beats [0:ROPE_CASE_COUNT*ROPE_BEATS-1];",
        "initial begin",
    ]

    for case_index, case in enumerate(cases):
        result = reference_rope(case)
        input_digest = hashlib.sha256(bytes(value & 0xFF for value in case.activations)).hexdigest()
        scale_digest = hashlib.sha256(
            b"".join((value & 0xFFFF).to_bytes(2, "little") for value in case.scales_q9)
        ).hexdigest()
        table_digest = hashlib.sha256(
            b"".join((value & 0xFFFF).to_bytes(2, "little") for value in case.cos_q15 + case.sin_q15)
        ).hexdigest()
        output_digest = hashlib.sha256(bytes(value & 0xFF for value in result.outputs)).hexdigest()
        sv_lines.append(f"  // rope case {case_index}: {case.name}")
        sv_lines.append(f"  rope_sequence_position[{case_index}] = 16'd{case.sequence_position};")
        sv_lines.append(f"  rope_expected_saturation[{case_index}] = 1'b{1 if result.saturation_seen else 0};")
        for beat_index, chunk in enumerate(_chunks(case.activations, LANES)):
            flat = case_index * ROPE_BEATS + beat_index
            sv_lines.append(f"  rope_input_beats[{flat}] = {_hex(pack_int8(chunk), 128)};")
        for beat_index, chunk in enumerate(_chunks(result.outputs, LANES)):
            flat = case_index * ROPE_BEATS + beat_index
            sv_lines.append(f"  rope_expected_beats[{flat}] = {_hex(pack_int8(chunk), 128)};")
        for beat_index in range(ROPE_BEATS):
            values = case.scales_q9[beat_index * LANES : (beat_index + 1) * LANES]
            cos_values = case.cos_q15[beat_index * LANES : (beat_index + 1) * LANES]
            sin_values = case.sin_q15[beat_index * LANES : (beat_index + 1) * LANES]
            for half_index, chunk in enumerate(_chunks(values, 8)):
                flat = case_index * ROPE_BEATS * 2 + beat_index * 2 + half_index
                sv_lines.append(f"  rope_scale_beats[{flat}] = {_hex(pack_int16(chunk), 128)};")
            for half_index, chunk in enumerate(_chunks(cos_values, 8)):
                flat = case_index * ROPE_BEATS * 2 + beat_index * 2 + half_index
                sv_lines.append(f"  rope_cos_beats[{flat}] = {_hex(pack_int16(chunk), 128)};")
            for half_index, chunk in enumerate(_chunks(sin_values, 8)):
                flat = case_index * ROPE_BEATS * 2 + beat_index * 2 + half_index
                sv_lines.append(f"  rope_sin_beats[{flat}] = {_hex(pack_int16(chunk), 128)};")
        records.append(
            {
                "name": case.name,
                "sequence_position": case.sequence_position,
                "saturation_seen": result.saturation_seen,
                "input_sha256": input_digest,
                "scale_sha256": scale_digest,
                "table_sha256": table_digest,
                "output_sha256": output_digest,
            }
        )

    sv_lines.append("end")
    OUT_SVH.write_text("\n".join(sv_lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "generator": "tools/gen_rope_vectors.py",
                "reference": "tools/ace2_rope_reference.py",
                "hidden_size": HIDDEN_SIZE,
                "head_dim": HEAD_DIM,
                "lanes": LANES,
                "beats": ROPE_BEATS,
                "cases": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
