#!/usr/bin/env python3
"""Generate deterministic residual-add vectors from the independent reference."""

from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path

from ace2_residual_reference import BEATS, HIDDEN_SIZE, pack_int8_beats, reference_residual_add


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "residual_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "residual_vectors.json"


def _cases() -> list[tuple[str, list[int], list[int]]]:
    cases = [
        ("zero_plus_ramp", [0] * HIDDEN_SIZE, [((index * 13) % 256) - 128 for index in range(HIDDEN_SIZE)]),
        ("cancel", [((index * 17) % 255) - 127 for index in range(HIDDEN_SIZE)],
         [-(((index * 17) % 255) - 127) for index in range(HIDDEN_SIZE)]),
        ("positive_saturation", [120] * HIDDEN_SIZE, [32] * HIDDEN_SIZE),
        ("negative_saturation", [-120] * HIDDEN_SIZE, [-32] * HIDDEN_SIZE),
    ]
    rng = random.Random(0xACE20801)
    for case_index in range(4):
        lhs = [rng.randint(-128, 127) for _ in range(HIDDEN_SIZE)]
        rhs = [rng.randint(-128, 127) for _ in range(HIDDEN_SIZE)]
        cases.append((f"seeded_random_{case_index}", lhs, rhs))
    return cases


def _hex(value: int, width: int) -> str:
    return f"{width}'h{value & ((1 << width) - 1):0{width // 4}x}"


def main() -> None:
    cases = _cases()
    records = []
    lines = [
        "// Generated by tools/gen_residual_vectors.py; do not edit by hand.",
        f"localparam integer RESIDUAL_CASE_COUNT = {len(cases)};",
        f"localparam integer RESIDUAL_BEATS = {BEATS};",
        "reg [127:0] residual_lhs_beats [0:RESIDUAL_CASE_COUNT*RESIDUAL_BEATS-1];",
        "reg [127:0] residual_rhs_beats [0:RESIDUAL_CASE_COUNT*RESIDUAL_BEATS-1];",
        "reg [127:0] residual_expected_beats [0:RESIDUAL_CASE_COUNT*RESIDUAL_BEATS-1];",
        "reg residual_expected_saturation [0:RESIDUAL_CASE_COUNT-1];",
        "initial begin",
    ]
    for case_index, (name, lhs, rhs) in enumerate(cases):
        outputs, saturated = reference_residual_add(lhs, rhs)
        lhs_beats = pack_int8_beats(lhs)
        rhs_beats = pack_int8_beats(rhs)
        output_beats = pack_int8_beats(outputs)
        records.append({
            "name": name,
            "lhs_sha256": hashlib.sha256(bytes(value & 0xFF for value in lhs)).hexdigest(),
            "rhs_sha256": hashlib.sha256(bytes(value & 0xFF for value in rhs)).hexdigest(),
            "output_sha256": hashlib.sha256(bytes(value & 0xFF for value in outputs)).hexdigest(),
            "saturation_seen": saturated,
        })
        lines.append(f"  residual_expected_saturation[{case_index}] = 1'b{int(saturated)};")
        for beat_index in range(BEATS):
            flat = case_index * BEATS + beat_index
            lines.append(f"  residual_lhs_beats[{flat}] = {_hex(lhs_beats[beat_index], 128)};")
            lines.append(f"  residual_rhs_beats[{flat}] = {_hex(rhs_beats[beat_index], 128)};")
            lines.append(f"  residual_expected_beats[{flat}] = {_hex(output_beats[beat_index], 128)};")
    lines.append("end")
    OUT_SVH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(json.dumps({
        "schema_version": 1,
        "generator": "tools/gen_residual_vectors.py",
        "reference": "tools/ace2_residual_reference.py",
        "hidden_size": HIDDEN_SIZE,
        "beats": BEATS,
        "cases": records,
    }, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
