#!/usr/bin/env python3
"""Generate deterministic boundary vectors for the DPRF standalone RTL."""

from __future__ import annotations

import json
from pathlib import Path

from ace2_down_projection_residual_fusion_reference import (
    fuse_lane_schedule_model,
    pack_scale32,
    workspace_proof,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "verification/generated/down_projection_residual_fusion_vectors.json"
OUT_SVH = ROOT / "verification/generated/down_projection_residual_fusion_vectors.svh"
UNIT = pack_scale32(0x8000, 0)
HALF = pack_scale32(0x8000, -1)


VALID_INPUTS = [
    (1, 2, UNIT, UNIT, UNIT, "unit_add"),
    (1, 0, HALF, UNIT, UNIT, "positive_half_to_even_zero"),
    (3, 0, HALF, UNIT, UNIT, "positive_one_point_five_to_even_two"),
    (-3, 0, HALF, UNIT, UNIT, "negative_one_point_five_to_even_two"),
    (127, 1, UNIT, UNIT, UNIT, "positive_saturation"),
    (-128, -1, UNIT, UNIT, UNIT, "negative_saturation"),
    (255, 0, HALF, UNIT, UNIT, "positive_127_point_5_tie_clamps"),
    (-257, 0, HALF, UNIT, UNIT, "negative_128_point_5_tie_stays_minus128"),
    (17, -9, pack_scale32(0xA123, -24), pack_scale32(0xFFFF, 4), pack_scale32(0x9000, -3), "exponent_extremes"),
    ((1 << 31) - 1, 127, pack_scale32(0xFFFF, 4), pack_scale32(0xFFFF, 4), pack_scale32(0x8000, -24), "maximum_positive_workspace"),
    (-(1 << 31), -128, pack_scale32(0xFFFF, 4), pack_scale32(0xFFFF, 4), pack_scale32(0x8000, -24), "maximum_negative_workspace"),
    (0, 0, pack_scale32(0xFFFF, -24), pack_scale32(0x8000, 4), pack_scale32(0xABCD, 1), "zero_numerator"),
]

INVALID_INPUTS = [
    (0, 0, 0x01008000, UNIT, UNIT, "reserved_byte_nonzero"),
    (0, 0, 0x00007FFF, UNIT, UNIT, "unnormalized_significand"),
    (0, 0, 0x00E78000, UNIT, UNIT, "exponent_below_minimum"),
    (0, 0, UNIT, 0x00058000, UNIT, "exponent_above_maximum"),
]


def sv_signed(width: int, value: int) -> str:
    return f"-{width}'sd{abs(value)}" if value < 0 else f"{width}'sd{value}"


def main() -> int:
    cases = []
    sv_lines = ["// Generated by tools/gen_down_projection_residual_fusion_vectors.py"]
    for accumulator, residual, accumulator_scale, residual_scale, destination_scale, name in VALID_INPUTS:
        result = fuse_lane_schedule_model(
            accumulator, residual, accumulator_scale, residual_scale, destination_scale
        )
        cases.append({
            "name": name,
            "valid": True,
            "inputs": {
                "accumulator_s32": accumulator,
                "residual_s8": residual,
                "accumulator_scale32": accumulator_scale,
                "residual_scale32": residual_scale,
                "destination_scale32": destination_scale,
            },
            "expected": result.__dict__,
        })
        sv_lines.append(
            "run_case("
            f"\"{name}\", {sv_signed(32, accumulator)}, {sv_signed(8, residual)}, "
            f"32'h{accumulator_scale:08x}, 32'h{residual_scale:08x}, "
            f"32'h{destination_scale:08x}, {sv_signed(8, result.output_s8)}, "
            f"96'sh{result.numerator_s96 & ((1 << 96) - 1):024x}, "
            f"64'h{result.denominator_u64:016x}, {sv_signed(8, result.common_exponent)}, "
            f"1'b{int(result.positive_saturation)}, 1'b{int(result.negative_saturation)}, "
            "1'b0, 1'b0, 5'd10);"
        )
    for accumulator, residual, accumulator_scale, residual_scale, destination_scale, name in INVALID_INPUTS:
        cases.append({
            "name": name,
            "valid": False,
            "inputs": {
                "accumulator_s32": accumulator,
                "residual_s8": residual,
                "accumulator_scale32": accumulator_scale,
                "residual_scale32": residual_scale,
                "destination_scale32": destination_scale,
            },
            "expected": {"descriptor_error": True, "latency_cycles": 0},
        })
        sv_lines.append(
            "run_case("
            f"\"{name}\", {sv_signed(32, accumulator)}, {sv_signed(8, residual)}, "
            f"32'h{accumulator_scale:08x}, 32'h{residual_scale:08x}, "
            f"32'h{destination_scale:08x}, 8'sd0, 96'sd0, 64'd0, 8'sd0, "
            "1'b0, 1'b0, 1'b1, 1'b0, 5'd0);"
        )
    payload = {
        "schema_version": 1,
        "contract_id": "shared_down_projection_residual_fusion_v1",
        "schedule": {
            "valid_start_to_out_valid_cycles": 10,
            "quotient_bits": 8,
            "algorithm": "exact_preclamp_then_one_shift_subtract_bit_per_cycle",
        },
        "workspace_proof": workspace_proof(),
        "cases": cases,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    OUT_SVH.write_text("\n".join(sv_lines) + "\n", encoding="utf-8")
    print(f"generated {OUT_JSON.relative_to(ROOT)} and {OUT_SVH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
