#!/usr/bin/env python3
"""Generate deterministic full-shape post-MLP residual vectors."""

from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path

from ace2_mlp_residual_reference import (
    BEATS,
    HIDDEN_SIZE,
    MlpResidualCase,
    pack_int8_beats,
    reference_mlp_residual_add,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "mlp_residual_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "mlp_residual_vectors.json"


def cases() -> list[MlpResidualCase]:
    rng = random.Random(0xACE21818)
    return [
        MlpResidualCase(
            name="post_mlp_balanced",
            down_projection=[((index * 29 + 17) % 161) - 80 for index in range(HIDDEN_SIZE)],
            residual_stream=[((index * 43 + 11) % 151) - 75 for index in range(HIDDEN_SIZE)],
        ),
        MlpResidualCase(
            name="post_mlp_mixed_saturation",
            down_projection=[120 if index & 1 else -120 for index in range(HIDDEN_SIZE)],
            residual_stream=[31 if index & 1 else -31 for index in range(HIDDEN_SIZE)],
        ),
        MlpResidualCase(
            name="post_mlp_cancellation",
            down_projection=[((index * 37) % 255) - 127 for index in range(HIDDEN_SIZE)],
            residual_stream=[-(((index * 37) % 255) - 127) for index in range(HIDDEN_SIZE)],
        ),
        MlpResidualCase(
            name="post_mlp_seeded_full_shape",
            down_projection=[rng.randint(-128, 127) for _ in range(HIDDEN_SIZE)],
            residual_stream=[rng.randint(-128, 127) for _ in range(HIDDEN_SIZE)],
        ),
    ]


def hex_value(value: int, width: int) -> str:
    return f"{width}'h{value & ((1 << width) - 1):0{width // 4}x}"


def digest(values: list[int]) -> str:
    return hashlib.sha256(bytes(value & 0xFF for value in values)).hexdigest()


def main() -> None:
    records = []
    lines = [
        "// Generated by tools/gen_mlp_residual_vectors.py; do not edit by hand.",
        f"localparam integer MLP_RESIDUAL_CASE_COUNT = {len(cases())};",
        f"localparam integer MLP_RESIDUAL_BEATS = {BEATS};",
        "reg [127:0] mlp_residual_down_beats [0:MLP_RESIDUAL_CASE_COUNT*MLP_RESIDUAL_BEATS-1];",
        "reg [127:0] mlp_residual_stream_beats [0:MLP_RESIDUAL_CASE_COUNT*MLP_RESIDUAL_BEATS-1];",
        "reg [127:0] mlp_residual_expected_beats [0:MLP_RESIDUAL_CASE_COUNT*MLP_RESIDUAL_BEATS-1];",
        "reg mlp_residual_expected_saturation [0:MLP_RESIDUAL_CASE_COUNT-1];",
        "initial begin",
    ]
    for case_index, case in enumerate(cases()):
        result = reference_mlp_residual_add(case)
        down_beats = pack_int8_beats(case.down_projection)
        stream_beats = pack_int8_beats(case.residual_stream)
        output_beats = pack_int8_beats(result.outputs)
        records.append(
            {
                "name": case.name,
                "down_projection_sha256": digest(case.down_projection),
                "residual_stream_sha256": digest(case.residual_stream),
                "output_sha256": digest(result.outputs),
                "saturation_seen": result.saturation_seen,
                "positive_saturation_count": result.positive_saturation_count,
                "negative_saturation_count": result.negative_saturation_count,
            }
        )
        lines.append(
            f"  mlp_residual_expected_saturation[{case_index}] = "
            f"1'b{int(result.saturation_seen)};"
        )
        for beat_index in range(BEATS):
            flat = case_index * BEATS + beat_index
            lines.append(
                f"  mlp_residual_down_beats[{flat}] = "
                f"{hex_value(down_beats[beat_index], 128)};"
            )
            lines.append(
                f"  mlp_residual_stream_beats[{flat}] = "
                f"{hex_value(stream_beats[beat_index], 128)};"
            )
            lines.append(
                f"  mlp_residual_expected_beats[{flat}] = "
                f"{hex_value(output_beats[beat_index], 128)};"
            )
    lines.append("end")
    OUT_SVH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "generator": "tools/gen_mlp_residual_vectors.py",
                "reference": "tools/ace2_mlp_residual_reference.py",
                "operator": "layer_0.mlp_residual_add",
                "hidden_size": HIDDEN_SIZE,
                "beats": BEATS,
                "cases": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
