#!/usr/bin/env python3
"""Generate deterministic focused vectors for dynamic Scale32 RTL."""

from __future__ import annotations

import json
from pathlib import Path

from ace2_dynamic_scale32_reference import (
    TaggedEvent,
    build_sidecar,
    dynamic_group,
    tagged_accumulate,
)
from ace2_quality_contracts import pack_scale32


ROOT = Path(__file__).resolve().parents[1]
JSON_OUT = ROOT / "verification/generated/dynamic_scale32_vectors.json"
SVH_OUT = ROOT / "verification/generated/dynamic_scale32_vectors.svh"


def make_case(name: str, values: list[int], base_scale32: int) -> dict[str, object]:
    result = dynamic_group(values, base_scale32)
    return {
        "name": name,
        "group_lanes": len(values),
        "base_scale32": base_scale32,
        "values": values,
        "delta": result.delta,
        "effective_scale32": result.effective_scale32,
        "mantissas": list(result.mantissas),
    }


def main() -> int:
    scale_one = pack_scale32(0x8000, 0)
    cases = [
        make_case("zero64", [0] * 64, scale_one),
        make_case("small64", [(-2, -1, 0, 1, 2)[index % 5] for index in range(64)], scale_one),
        make_case("tie255_64", [255 if index == 0 else -255 if index == 1 else 0 for index in range(64)], scale_one),
        make_case("base_floor64", [1 if index & 1 else -1 for index in range(64)], pack_scale32(0x9234, -24)),
        make_case("wide128", [((index * 73) % 2001) - 1000 for index in range(128)], pack_scale32(0xC000, -3)),
    ]
    sidecar = build_sidecar(
        payload_addr=0x1000,
        group_lanes=64,
        producer_tag=0x1234,
        layer_id=7,
        producer_opcode=1,
        tensor_elements=128,
        model_identity=0x0123456789ABCDEF,
        deltas=(-5, 2),
        base_scales=(scale_one, scale_one),
    )
    accumulator = tagged_accumulate(
        (
            TaggedEvent(3, scale_one, scale_one),
            TaggedEvent(-1, scale_one, scale_one),
        )
    )
    wide128_mantissas = cases[4]["mantissas"]
    wide128_packed_hex = "".join(
        f"{int(value) & 0xFF:02x}" for value in reversed(wide128_mantissas)
    )
    document = {
        "schema_version": 1,
        "contract_id": "shared_token_group_dynamic_scale32_v1",
        "numeric_acceptance": "bit_exact_fixed_point_vector_match",
        "cases": cases,
        "sidecar_hex": sidecar.hex(),
        "tagged_accumulator": {
            "canonical_exponent": -78,
            "value_hex_160": f"{accumulator & ((1 << 160) - 1):040x}",
        },
    }
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    lines = [
        "// Generated by tools/gen_dynamic_scale32_vectors.py",
        "localparam logic [31:0] DS32_SCALE_ONE = 32'h00008000;",
        "localparam logic [31:0] DS32_SCALE_FLOOR = 32'h00e89234;",
        "localparam logic [31:0] DS32_SCALE_WIDE = 32'h00fdc000;",
        "localparam logic [511:0] DS32_SIDECAR = 512'h" + sidecar[::-1].hex() + ";",
        "localparam logic signed [159:0] DS32_ACC_EXPECTED = 160'h"
        + f"{accumulator & ((1 << 160) - 1):040x};",
        "localparam logic [31:0] DS32_EXPECTED_SCALE_0 = 32'h00008000;",
        "localparam logic [31:0] DS32_EXPECTED_SCALE_1 = 32'h00fb8000;",
        "localparam logic [31:0] DS32_EXPECTED_SCALE_2 = 32'h00028000;",
        "localparam logic [31:0] DS32_EXPECTED_SCALE_3 = 32'h00e89234;",
        "localparam logic [31:0] DS32_EXPECTED_SCALE_4 = 32'h0000c000;",
        "localparam logic signed [1023:0] DS32_EXPECTED_MANTISSAS_4 = 1024'h"
        + wide128_packed_hex
        + ";",
    ]
    SVH_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"ACE2_DYNAMIC_SCALE32_VECTOR_GENERATION_PASS cases={len(cases)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
