#!/usr/bin/env python3
"""Generate ACE-2 softmax RTL vectors from the Python reference."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from ace2_softmax_reference import (
    CONTEXT_MAX,
    SoftmaxCase,
    pack_uint16,
    reference_softmax,
)


ROOT = Path(__file__).resolve().parents[1]
OUT_SVH = ROOT / "verification" / "generated" / "softmax_vectors.svh"
OUT_JSON = ROOT / "verification" / "generated" / "softmax_vectors.json"


def _cases() -> list[SoftmaxCase]:
    return [
        SoftmaxCase("single_token_identity", [37]),
        SoftmaxCase("two_token_tie", [128, 128]),
        SoftmaxCase("three_token_rounding", [0, -64, -512]),
        SoftmaxCase("eight_token_mixed", [512, 448, 256, 0, -256, -512, -1024, -4096]),
        SoftmaxCase("dominant_and_masked_tail", [3072, 0, -2048, -8192, -16384]),
    ]


def _hex(value: int, width_bits: int) -> str:
    return f"{width_bits}'h{value & ((1 << width_bits) - 1):0{width_bits // 4}x}"


def _digest_int16(values: list[int]) -> str:
    return hashlib.sha256(
        b"".join((value & 0xFFFF).to_bytes(2, "little") for value in values)
    ).hexdigest()


def main() -> None:
    OUT_SVH.parent.mkdir(parents=True, exist_ok=True)
    cases = _cases()
    records = []
    sv_lines = [
        "// Generated by tools/gen_softmax_vectors.py; do not edit by hand.",
        f"localparam integer SOFTMAX_CASE_COUNT = {len(cases)};",
        f"localparam integer SOFTMAX_CONTEXT_MAX = {CONTEXT_MAX};",
        "reg [15:0] softmax_context_count [0:SOFTMAX_CASE_COUNT-1];",
        "reg [16*8-1:0] softmax_score_word [0:SOFTMAX_CASE_COUNT-1];",
        "reg [16*8-1:0] softmax_expected_exp_word [0:SOFTMAX_CASE_COUNT-1];",
        "reg [18:0] softmax_expected_exp_sum [0:SOFTMAX_CASE_COUNT-1];",
        "reg [16*8-1:0] softmax_expected_word [0:SOFTMAX_CASE_COUNT-1];",
        "initial begin",
    ]

    for case_index, case in enumerate(cases):
        result = reference_softmax(case)
        padded_scores = case.scores_q6_9 + [0 for _ in range(CONTEXT_MAX - len(case.scores_q6_9))]
        sv_lines.append(f"  // softmax case {case_index}: {case.name}")
        sv_lines.append(f"  softmax_context_count[{case_index}] = 16'd{len(case.scores_q6_9)};")
        sv_lines.append(f"  softmax_score_word[{case_index}] = {_hex(pack_uint16(padded_scores), 128)};")
        sv_lines.append(f"  softmax_expected_exp_word[{case_index}] = {_hex(pack_uint16(result.exp_weights_q15), 128)};")
        sv_lines.append(f"  softmax_expected_exp_sum[{case_index}] = 19'd{result.exp_sum_q15};")
        sv_lines.append(f"  softmax_expected_word[{case_index}] = {_hex(pack_uint16(result.probabilities_q0_15), 128)};")
        records.append(
            {
                "name": case.name,
                "context_count": len(case.scores_q6_9),
                "score_sha256": _digest_int16(case.scores_q6_9),
                "exp_weight_sha256": _digest_int16(result.exp_weights_q15),
                "probability_sha256": _digest_int16(result.probabilities_q0_15),
                "exp_sum_q15": result.exp_sum_q15,
                "max_score_q6_9": result.max_score_q6_9,
            }
        )

    sv_lines.append("end")
    OUT_SVH.write_text("\n".join(sv_lines) + "\n", encoding="utf-8")
    OUT_JSON.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "generator": "tools/gen_softmax_vectors.py",
                "reference": "tools/ace2_softmax_reference.py",
                "context_max": CONTEXT_MAX,
                "score_format": "signed_int16 Q6.9",
                "probability_format": "unsigned_int16 Q0.15",
                "cases": records,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
